version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "psplus_backend"
    image: firya/psplus
    volumes:
      - ./backend/src:/app/src
    restart: always
    environment:
      - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - TELEGRAM_DEFAULT_ADMIN=$TELEGRAM_DEFAULT_ADMIN
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - PS_STORE_HASH=$PS_STORE_HASH
      - MONGO_USER=$MONGO_USERNAME
      - MONGO_PASS=$MONGO_PASSWORD
    depends_on:
      - mongo

  mongo:
    container_name: "psplus_mongo"
    image: mongo
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=server
    ports:
      - "27018:27017"

networks:
  default:
    name: nginx-proxy
